name: Notify
description: Send a notification via webhook to Slack.

inputs:
  webhook_url:
    description: Slack trigger webhook URL for this event
    required: true
  slack_id:
    description: Slack user/owner id (from secrets.SLACKID)
    required: true
  data:
    description: JSON stringify data
    required: false

runs:
  using: composite
  steps:
    - name: Send notification
      uses: fjogeleit/http-request-action@v2
      with:
        url: ${{ inputs.webhook_url }}
        method: "POST"
        customHeaders: '{"Content-Type": "application/json"}'
        data: ${{ inputs.data != '' && inputs.data || format('{{"owner":"{0}","repoName":"{1}","branch":"{2}","buildUrl":"{3}/{1}/actions/runs/{4}","slackUserId":"{5}"}}', github.repository_owner, github.repository, github.ref_name || github.head_ref, github.server_url, github.run_id, inputs.slack_id) }}
